### ISSUE TITLE
Page Navigation on application log frontend

### ISSUE THREAD

**Issue by ShainaBagri** [helenewillits/JobMe#4]
Add button opens up new page which contains empty slots for the new entry which the user must fill in. There must also be a submit and a cancel button on the new page. Make sure user inputs have been agreed upon.
SPRINT 2 : An edit button must appear next to each entry in the application log. This edit button opens a page similar to the add button, except the slots are filled with the existing data. There is also a submit and delete button on this new page.

NOTE: If edit functionality implemented, we will likely use the same page to add and edit entries, in which case the cancel button should be a delete button. This edit button will take the place of the current delete button next to each entry, and the delete button within the new page will then contain the functionality of the original delete button.

**Comment by ShainaBagri** [comment]
Time Estimate: 3 hours

**Comment by maxmoneycash** [comment]
Time Actual: 3 hours
